[mypy]
python_version = 3.13
pretty = True
show_error_codes = True
warn_unused_configs = True
ignore_missing_imports = True
follow_imports = silent
check_untyped_defs = True
no_implicit_optional = True
explicit_package_bases = True
