"""RoutePilot live provider ports, adapters and resilient gateway.

RAG retrieves versioned knowledge; this package obtains time-sensitive facts
such as routes, weather and opening status.  A missing provider always reports
``PROVIDER_UNAVAILABLE`` and is never replaced with mock facts.
"""

from .amap import AMAP_API_VERSION, AMAP_BASE_URL, AMAP_PROVIDER_ID, AMapProvider
from .errors import (
    ProviderAuthenticationError,
    ProviderCancelledError,
    ProviderCircuitOpenError,
    ProviderError,
    ProviderIdempotencyConflictError,
    ProviderInputError,
    ProviderNotAllowedError,
    ProviderRateLimitedError,
    ProviderResponseError,
    ProviderTimeoutError,
    ProviderUnavailableError,
)
from .gateway import GatewayPolicy, ProviderGateway, build_default_provider_gateway
from .models import (
    Coordinate,
    FreshnessStatus,
    GeocodeCandidate,
    GeocodeRequest,
    GeocodeResult,
    OpeningHoursEntry,
    OpeningHoursRequest,
    OpeningHoursResult,
    Place,
    PlaceSearchRequest,
    PlaceSearchResult,
    ProviderCapability,
    ProviderDescriptor,
    ProviderHealth,
    ProviderProvenance,
    RouteMatrixCell,
    RouteMatrixRequest,
    RouteMatrixResult,
    RouteMode,
    WeatherPeriod,
    WeatherRequest,
    WeatherResult,
    utc_now,
)
from .ports import (
    CacheScope,
    GeocodePort,
    OpeningHoursPort,
    PlaceSearchPort,
    ProviderCallContext,
    ProviderPort,
    RouteMatrixPort,
    WeatherPort,
)
from .settings import KNOWN_PROVIDER_IDS, ProviderSettings
from .unavailable import UnavailableProvider

__all__ = [
    "AMAP_API_VERSION",
    "AMAP_BASE_URL",
    "AMAP_PROVIDER_ID",
    "AMapProvider",
    "CacheScope",
    "Coordinate",
    "FreshnessStatus",
    "GatewayPolicy",
    "GeocodeCandidate",
    "GeocodePort",
    "GeocodeRequest",
    "GeocodeResult",
    "KNOWN_PROVIDER_IDS",
    "OpeningHoursEntry",
    "OpeningHoursPort",
    "OpeningHoursRequest",
    "OpeningHoursResult",
    "Place",
    "PlaceSearchPort",
    "PlaceSearchRequest",
    "PlaceSearchResult",
    "ProviderAuthenticationError",
    "ProviderCallContext",
    "ProviderCancelledError",
    "ProviderCapability",
    "ProviderCircuitOpenError",
    "ProviderError",
    "ProviderGateway",
    "ProviderDescriptor",
    "ProviderHealth",
    "ProviderIdempotencyConflictError",
    "ProviderInputError",
    "ProviderNotAllowedError",
    "ProviderPort",
    "ProviderRateLimitedError",
    "ProviderResponseError",
    "ProviderSettings",
    "ProviderProvenance",
    "ProviderTimeoutError",
    "ProviderUnavailableError",
    "RouteMatrixPort",
    "RouteMatrixCell",
    "RouteMatrixRequest",
    "RouteMatrixResult",
    "RouteMode",
    "UnavailableProvider",
    "WeatherPeriod",
    "WeatherPort",
    "WeatherRequest",
    "WeatherResult",
    "build_default_provider_gateway",
    "utc_now",
]
