export const MAX_TRIP_DAYS = Number(process.env.TRAVELPILOT_MAX_TRIP_DAYS || 7);

export const BEIJING_AREA_ANCHORS: Record<string, { lng: number; lat: number; district: string }> = {
  北京: { lng: 116.4074, lat: 39.9042, district: '北京市' },
  前门: { lng: 116.3976, lat: 39.9006, district: '东城区' },
  故宫: { lng: 116.3972, lat: 39.9163, district: '东城区' },
  什刹海: { lng: 116.3844, lat: 39.9417, district: '西城区' },
  后海: { lng: 116.3844, lat: 39.9417, district: '西城区' },
  天坛: { lng: 116.4108, lat: 39.8819, district: '东城区' },
  颐和园: { lng: 116.2755, lat: 39.9999, district: '海淀区' },
  圆明园: { lng: 116.3099, lat: 40.0084, district: '海淀区' },
  王府井: { lng: 116.4114, lat: 39.9149, district: '东城区' },
  天安门: { lng: 116.3975, lat: 39.9087, district: '东城区' },
  北海: { lng: 116.3907, lat: 39.9289, district: '西城区' },
  景山: { lng: 116.3966, lat: 39.9259, district: '西城区' },
  南锣鼓巷: { lng: 116.4032, lat: 39.9371, district: '东城区' },
  西单: { lng: 116.3742, lat: 39.9072, district: '西城区' },
  雍和宫: { lng: 116.4174, lat: 39.9471, district: '东城区' },
  三里屯: { lng: 116.4547, lat: 39.9336, district: '朝阳区' },
  '798': { lng: 116.5015, lat: 39.9897, district: '朝阳区' },
  奥林匹克公园: { lng: 116.3966, lat: 40.0080, district: '朝阳区' },
  长城: { lng: 116.0167, lat: 40.3562, district: '延庆区' },
  环球影城: { lng: 116.6806, lat: 39.8577, district: '通州区' },
  北京环球度假区: { lng: 116.6806, lat: 39.8577, district: '通州区' },
};

export const BEIJING_CLASSIC_DAY_AREAS = [
  '故宫',
  '天坛',
  '什刹海',
  '颐和园',
  '南锣鼓巷',
  '雍和宫',
  '北海',
  '天安门',
  '王府井',
  '奥林匹克公园',
  '环球影城',
];

export const LANDMARK_FIXTURE_POIS = [
  {
    poi_id: 'fixture_badaling_great_wall',
    name: '八达岭长城',
    district: '延庆区',
    area: '长城',
    category: '景区',
    poi_type: 'culture',
    address: '北京市延庆区G6京藏高速58号出口',
    lng: 116.016736,
    lat: 40.356213,
    rating: 4.8,
    avg_cost: 40,
    review_count: 12000,
    open_time: '07:30',
    close_time: '17:00',
    suggested_duration_min: 180,
    planning_tags: ['landmark', 'scene:outdoor', 'theme:great_wall', 'walk:high', 'classic_first_timer'],
    evidence_tags: ['北京经典地标', '适合半日或一日游', '与市区 POI 转场较远'],
    queue_risk: 'high',
    value_for_money: 'medium',
    family_friendliness: 'medium',
    environment_quality: 'high',
    meal_type: 'invalid',
    is_lunch_suitable: false,
    is_coffee_stop: false,
    is_meal_stop: false,
  },
  {
    poi_id: 'fixture_summer_palace',
    name: '颐和园',
    district: '海淀区',
    area: '颐和园',
    category: '景区',
    poi_type: 'culture',
    address: '北京市海淀区新建宫门路19号',
    lng: 116.2755,
    lat: 39.9999,
    rating: 4.8,
    avg_cost: 30,
    review_count: 12000,
    open_time: '06:30',
    close_time: '18:00',
    suggested_duration_min: 180,
    planning_tags: ['landmark', 'scene:outdoor', 'theme:garden', 'classic_first_timer', 'walk:medium'],
    evidence_tags: ['北京经典地标', '皇家园林', '适合半日游'],
    queue_risk: 'medium',
    value_for_money: 'high',
    family_friendliness: 'medium',
    environment_quality: 'high',
    meal_type: 'invalid',
    is_lunch_suitable: false,
    is_coffee_stop: false,
    is_meal_stop: false,
  },
  {
    poi_id: 'fixture_yuanmingyuan_park',
    name: '圆明园遗址公园',
    district: '海淀区',
    area: '圆明园',
    category: '景区',
    poi_type: 'culture',
    address: '北京市海淀区清华西路28号',
    lng: 116.3099,
    lat: 40.0084,
    rating: 4.7,
    avg_cost: 10,
    review_count: 9000,
    open_time: '07:00',
    close_time: '19:00',
    suggested_duration_min: 150,
    planning_tags: ['landmark', 'scene:outdoor', 'theme:garden', 'classic_first_timer', 'walk:medium'],
    evidence_tags: ['北京经典园林遗址', '适合与颐和园组成海淀西北线'],
    queue_risk: 'medium',
    value_for_money: 'high',
    family_friendliness: 'medium',
    environment_quality: 'high',
    meal_type: 'invalid',
    is_lunch_suitable: false,
    is_coffee_stop: false,
    is_meal_stop: false,
  },
  {
    poi_id: 'fixture_tingliguan_summer_palace',
    name: '听鹂馆饭庄（颐和园内）',
    district: '海淀区',
    area: '颐和园',
    category: 'dining',
    poi_type: 'food',
    address: '北京市海淀区颐和园内',
    lng: 116.2742,
    lat: 39.9992,
    rating: 4.5,
    avg_cost: 180,
    review_count: 1800,
    open_time: '11:00',
    close_time: '20:30',
    suggested_duration_min: 75,
    planning_tags: ['dining', 'lunch', 'classic_beijing_food', 'area:颐和园'],
    evidence_tags: ['颐和园内餐饮锚点', '适合颐和园日午餐'],
    queue_risk: 'medium',
    value_for_money: 'medium',
    family_friendliness: 'medium',
    environment_quality: 'high',
    meal_type: 'meal',
    is_lunch_suitable: true,
    is_coffee_stop: false,
    is_meal_stop: true,
  },
  {
    poi_id: 'fixture_badaling_great_wall_museum',
    name: '中国长城博物馆',
    district: '延庆区',
    area: '长城',
    category: 'museum',
    poi_type: 'culture',
    address: '北京市延庆区八达岭长城景区内',
    lng: 116.0107,
    lat: 40.3598,
    rating: 4.5,
    avg_cost: 0,
    review_count: 3200,
    open_time: '09:00',
    close_time: '16:30',
    suggested_duration_min: 75,
    planning_tags: ['landmark', 'scene:indoor', 'theme:great_wall', 'classic_first_timer'],
    evidence_tags: ['八达岭长城同区补充点', '适合长城日作为室内补充'],
    queue_risk: 'medium',
    value_for_money: 'high',
    family_friendliness: 'medium',
    environment_quality: 'medium',
    meal_type: 'invalid',
    is_lunch_suitable: false,
    is_coffee_stop: false,
    is_meal_stop: false,
  },
  {
    poi_id: 'fixture_badaling_lunch_anchor',
    name: '八达岭长城景区午餐点',
    district: '延庆区',
    area: '长城',
    category: 'dining',
    poi_type: 'food',
    address: '北京市延庆区八达岭长城景区周边',
    lng: 116.0185,
    lat: 40.3569,
    rating: 4.1,
    avg_cost: 80,
    review_count: 0,
    open_time: '10:30',
    close_time: '17:00',
    suggested_duration_min: 60,
    planning_tags: ['dining', 'lunch', 'area:长城', 'needs_address_confirmation'],
    evidence_tags: ['本地餐饮库未覆盖八达岭景区细粒度餐厅，按景区午餐锚点估算'],
    queue_risk: 'unknown',
    value_for_money: 'unknown',
    family_friendliness: 'medium',
    environment_quality: 'medium',
    meal_type: 'meal',
    is_lunch_suitable: true,
    is_coffee_stop: false,
    is_meal_stop: true,
  },
  {
    poi_id: 'fixture_universal_beijing_resort',
    name: '北京环球度假区',
    district: '通州区',
    area: '环球影城',
    category: 'theme_park',
    poi_type: 'culture',
    address: '北京市通州区北京环球度假区',
    lng: 116.6806,
    lat: 39.8577,
    rating: 4.7,
    avg_cost: 500,
    review_count: 10000,
    open_time: '09:00',
    close_time: '21:00',
    suggested_duration_min: 360,
    planning_tags: ['landmark', 'theme_park', 'classic_family', 'walk:high'],
    evidence_tags: ['北京主题乐园目的地', '通常适合单独安排一整天'],
    queue_risk: 'high',
    value_for_money: 'medium',
    family_friendliness: 'high',
    environment_quality: 'high',
    meal_type: 'invalid',
    is_lunch_suitable: false,
    is_coffee_stop: false,
    is_meal_stop: false,
  },
  {
    poi_id: 'fixture_universal_citywalk',
    name: '北京环球城市大道',
    district: '通州区',
    area: '环球影城',
    category: 'entertainment',
    poi_type: 'culture',
    address: '北京市通州区北京环球城市大道',
    lng: 116.6819,
    lat: 39.8582,
    rating: 4.5,
    avg_cost: 0,
    review_count: 6000,
    open_time: '08:00',
    close_time: '22:00',
    suggested_duration_min: 90,
    planning_tags: ['landmark', 'entertainment', 'theme_park_support'],
    evidence_tags: ['适合环球影城日餐饮和傍晚补充'],
    queue_risk: 'medium',
    value_for_money: 'medium',
    family_friendliness: 'high',
    environment_quality: 'high',
    meal_type: 'invalid',
    is_lunch_suitable: false,
    is_coffee_stop: false,
    is_meal_stop: false,
  },
  {
    poi_id: 'fixture_universal_citywalk_lunch',
    name: '环球城市大道午餐',
    district: '通州区',
    area: '环球影城',
    category: 'dining',
    poi_type: 'food',
    address: '北京市通州区北京环球城市大道餐饮区',
    lng: 116.6814,
    lat: 39.8586,
    rating: 4.3,
    avg_cost: 120,
    review_count: 0,
    open_time: '10:30',
    close_time: '21:30',
    suggested_duration_min: 60,
    planning_tags: ['dining', 'lunch', 'area:环球影城', 'needs_address_confirmation'],
    evidence_tags: ['环球影城日餐饮锚点，具体店铺可按现场排队情况选择'],
    queue_risk: 'medium',
    value_for_money: 'medium',
    family_friendliness: 'high',
    environment_quality: 'medium',
    meal_type: 'meal',
    is_lunch_suitable: true,
    is_coffee_stop: false,
    is_meal_stop: true,
  },
] as const;
